# Generated by Django 5.1.1 on 2024-09-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_questiontitlesection_question'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_title',
            field=models.ManyToManyField(blank=True, related_name='completed_title', to='course.coursetitle'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='course_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursetitle'),
        ),
    ]
