# Generated by Django 5.1.1 on 2024-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_userprogress_completed_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='progress_titles',
            field=models.FloatField(default=0.0),
        ),
    ]
