# Generated by Django 5.1.1 on 2024-09-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_userprogress_progress_titles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
