# Generated by Django 5.1.1 on 2024-09-17 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0021_alter_questiontitlesection_question'),
        ('progress', '0004_delete_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('progress_percentage', models.FloatField(default=0)),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='course.coursetitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
                ('viewed_subtitles', models.ManyToManyField(blank=True, related_name='user_subtitle_progress', to='course.coursesubtitle')),
            ],
        ),
    ]
