# Generated by Django 5.1.1 on 2024-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_remove_courseintroduction_introduction_and_more'),
        ('progress', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_titles',
            field=models.ManyToManyField(blank=True, related_name='completed_titles', to='course.coursetitle'),
        ),
    ]
