# Generated by Django 5.1.1 on 2024-09-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_userprogress_completed_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='viewed_subtitles',
        ),
    ]
