# Generated by Django 5.1.1 on 2024-09-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_remove_userprogress_viewed_subtitles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='completed',
            new_name='viewed',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_titles',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='progress_percentage',
        ),
    ]
