# Generated by Django 5.1.1 on 2024-09-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question',
        ),
    ]
