# Generated by Django 5.1.1 on 2024-09-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, upload_to='static/course_videos/'),
        ),
        migrations.CreateModel(
            name='CourseSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='course.coursetitle')),
            ],
        ),
    ]
