# Generated by Django 5.1.1 on 2024-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_video_coursesubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubtitle',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
