# Generated by Django 5.1.1 on 2024-09-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursesubtitle_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesubtitle',
            old_name='subtitle',
            new_name='chapters',
        ),
        migrations.AlterField(
            model_name='coursesubtitle',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.coursetitle'),
        ),
    ]
