# Generated by Django 5.1.1 on 2024-09-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_subtitle_coursesubtitle_chapters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubtitle',
            name='course',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubtitle',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course'),
            preserve_default=False,
        ),
    ]
