# Generated by Django 5.1.1 on 2024-09-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursesubtitle_course_coursesubtitle_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='static/course_images/'),
        ),
    ]
