# Generated by Django 5.1.1 on 2024-09-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_is_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetitle',
            old_name='title',
            new_name='chapter',
        ),
    ]
