# Generated by Django 5.1.1 on 2024-09-13 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_title_coursetitle_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesubtitle',
            old_name='chapters',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='coursesubtitle',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='course.coursetitle'),
        ),
    ]
