# Generated by Django 5.1.1 on 2024-09-13 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_chapters_coursesubtitle_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubtitle',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='course.coursetitle'),
        ),
    ]
