# Generated by Django 5.1.1 on 2024-09-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_coursesubtitle_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubtitle',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='course.coursetitle'),
        ),
    ]
