# Generated by Django 5.1.1 on 2024-09-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_coursesubtitle_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubtitle',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
