# Generated by Django 5.1.1 on 2024-09-16 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_coursesubtitle_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTitleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4')], max_length=10)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_id', to='course.coursesubtitle')),
            ],
        ),
    ]
