# Generated by Django 5.1.1 on 2024-09-16 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_questiontitlesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontitlesection',
            name='section_id',
        ),
        migrations.AddField(
            model_name='questiontitlesection',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='course.coursesubtitle'),
            preserve_default=False,
        ),
    ]
