# Generated by Django 5.1.1 on 2024-09-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_section', to='course.coursesubtitle'),
        ),
    ]
