# Generated by Django 5.1.1 on 2024-09-16 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_subsection_sub_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='sub_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_section', to='course.coursesubtitle'),
            preserve_default=False,
        ),
    ]
