# Generated by Django 5.1.1 on 2024-09-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_subsection_sub_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='content',
        ),
        migrations.CreateModel(
            name='SubSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sub_section_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subsection')),
            ],
        ),
    ]
