# Generated by Django 5.1.1 on 2024-09-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_subsection_content_subsectioncontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectioncontent',
            name='sub_section_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_section_content', to='course.subsection'),
        ),
    ]
