# Generated by Django 5.1.1 on 2024-09-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_subsectioncontent_sub_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontitlesection',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='course.coursetitle'),
        ),
    ]
