# Generated by Django 5.1.1 on 2024-09-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_courseintroduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseintroduction',
            old_name='name',
            new_name='introduction',
        ),
        migrations.RemoveField(
            model_name='courseintroduction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courseintroduction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courseintroduction',
            name='features',
        ),
        migrations.RemoveField(
            model_name='courseintroduction',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='courseintroduction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='courseintroduction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='courseintroduction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='courseintroduction',
            name='course_intro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_intro', to='course.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseIntroductionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/course_intro/')),
                ('features', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intro_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_view', to='course.courseintroduction')),
            ],
        ),
    ]
