# Generated by Django 5.1.1 on 2024-09-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_rename_name_courseintroduction_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseintroductionview',
            name='features',
        ),
        migrations.RemoveField(
            model_name='courseintroductionview',
            name='price',
        ),
    ]
