# Generated by Django 5.1.1 on 2024-09-17 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_remove_courseintroductionview_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseintroduction',
            name='introduction',
        ),
        migrations.AddField(
            model_name='courseintroduction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseintroduction',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseintroduction',
            name='headline',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseintroduction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/course_intro/'),
        ),
        migrations.AddField(
            model_name='courseintroduction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CourseIntroductionView',
        ),
    ]
