# Generated by Django 5.1.1 on 2024-09-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_courseexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsectioncontent',
            name='code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsectioncontent',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
