# Generated by Django 5.1.1 on 2024-09-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_subsectioncontent_code_subsectioncontent_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsectioncontent',
            options={'ordering': ['priority']},
        ),
    ]
