# Generated by Django 5.1.1 on 2024-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_titleinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleinteraction',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
