# Generated by Django 5.1.1 on 2024-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_titleinteraction_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsectioncontent',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='static/SubSectionContent/'),
        ),
    ]
