# Generated by Django 5.1.1 on 2024-10-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_subsectioncontent_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectioncontent',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='static/SubSectionContent/sounds/'),
        ),
    ]
