# Generated by Django 5.1.1 on 2024-09-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='plan',
        ),
        migrations.DeleteModel(
            name='CoursePlan',
        ),
    ]
