# Generated by Django 5.1.1 on 2024-09-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_courseplan_factor_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseplan',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courseplan',
            name='start_time',
        ),
        migrations.AddField(
            model_name='courseplan',
            name='month',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
