# Generated by Django 5.1.1 on 2024-09-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_courseplan_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='price',
        ),
        migrations.AddField(
            model_name='courseplan',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
