# Generated by Django 5.1.1 on 2024-09-26 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_factor_price_courseplan_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payer_identity', models.CharField(help_text='ایمیل یا شماره موبایل پرداخت\u200cکننده', max_length=255)),
                ('payer_name', models.CharField(blank=True, help_text='نام پرداخت\u200cکننده', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_ref_id', models.CharField(blank=True, help_text='کد ارجاع کاربر برای شناسایی پرداخت', max_length=100, null=True, unique=True)),
                ('return_url', models.URLField(help_text='آدرس بازگشت پس از تکمیل پرداخت')),
                ('is_paid', models.BooleanField(default=False)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='کد ارجاع پی\u200cپینگ', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
