# Generated by Django 5.1.1 on 2024-09-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='return_url',
        ),
    ]
