# Generated by Django 5.1.1 on 2024-09-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_return_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.CreateModel(
            name='PaymentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255)),
                ('refid', models.CharField(max_length=255)),
                ('clientrefid', models.CharField(max_length=255)),
                ('cardnumber', models.CharField(max_length=255)),
                ('cardhashpan', models.CharField(max_length=255)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='payment.payment')),
            ],
        ),
    ]
