# Generated by Django 5.1.1 on 2024-09-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_payment_is_paid_paymentstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cardhashpan',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
