# Generated by Django 5.1.1 on 2024-09-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_cardhashpan_payment_cardnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cardhashpan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client_ref_id',
        ),
    ]
