# Generated by Django 5.1.1 on 2024-09-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_payment_cardhashpan_remove_payment_cardnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ref_id',
            new_name='clientrefid',
        ),
    ]
