# Generated by Django 5.1.1 on 2024-09-27 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_rename_ref_id_payment_clientrefid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstats',
            name='payment',
        ),
        migrations.AlterModelOptions(
            name='factor',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='factor',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='cardhashpan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='clientrefid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='کد ارجاع پی\u200cپینگ', unique=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='payer_identity',
            field=models.CharField(default=1, help_text='ایمیل یا شماره موبایل پرداخت\u200cکننده', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factor',
            name='payer_name',
            field=models.CharField(blank=True, help_text='نام پرداخت\u200cکننده', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='payment_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='refid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentStats',
        ),
    ]
