# Generated by Django 5.1.1 on 2024-09-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_remove_paymentstats_payment_alter_factor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='cardhashpan',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='cardnumber',
        ),
    ]
