# Generated by Django 5.1.1 on 2024-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_factor_cardhashpan_remove_factor_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
