# Generated by Django 5.1.1 on 2024-09-28 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_alter_subsectioncontent_options'),
        ('payment', '0014_courseplan_unlimited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
