# Generated by Django 5.1.1 on 2024-09-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_moshaver',
        ),
    ]
