# Generated by Django 5.1.1 on 2024-09-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0004_alter_customuser_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='کاربر فعال'),
        ),
    ]
