# Generated by Django 5.1.1 on 2024-09-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_is_pro'),
        ('eriadu_auth', '0008_customuser_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='course.course'),
        ),
    ]
