# Generated by Django 5.1.1 on 2024-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0009_customuser_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='static/users/profile/'),
        ),
    ]
