# Generated by Django 5.1.1 on 2024-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0010_customuser_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
