# Generated by Django 5.1.1 on 2024-09-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0011_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='limited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eriadu_auth.limitedaccess'),
        ),
    ]
