# Generated by Django 5.1.1 on 2024-09-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0012_limitedaccess_customuser_unlimited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedaccess',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='limitedaccess',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
