# Generated by Django 5.1.1 on 2024-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0014_usercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='course_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='user_course',
            new_name='user',
        ),
    ]
