# Generated by Django 5.1.1 on 2024-10-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_subsectioncontent_sound'),
        ('eriadu_auth', '0015_rename_course_name_usercourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', unique=True),
        ),
    ]
