# Generated by Django 5.1.1 on 2024-10-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_subsectioncontent_sound'),
        ('eriadu_auth', '0016_alter_usercourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
