# Generated by Django 5.1.1 on 2024-10-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_subsectioncontent_sound'),
        ('eriadu_auth', '0018_alter_usercourse_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
    ]
