# Generated by Django 5.1.1 on 2024-10-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0020_customuser_created_alter_customuser_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
