# Generated by Django 5.1.1 on 2024-10-14 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0021_customuser_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits.', regex='/((0?9)|(\\+?989))\\d{2}\\W?\\d{3}\\W?\\d{4}/g')]),
        ),
    ]
