# Generated by Django 5.1.1 on 2024-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0024_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
