# Generated by Django 5.1.1 on 2024-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriadu_auth', '0025_alter_useractivity_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
